FROM ruby:2.7.1-slim

WORKDIR /opt/microservices/

COPY bookinfo/src/details/details.rb .
ENV ENABLE_EXTERNAL_BOOK_SERVICE=true
ENV SERVICES_DOMAIN=""
ENV DETAILS_HOSTNAME="details"
ENV RATINGS_HOSTNAME="ratings" 
ENV REVIEWS_HOSTNAME="reviews"
ENV TEAM_ID="29"
EXPOSE 7070

CMD ["ruby", "details.rb", "7070"]