apiVersion: v1
kind: Service
metadata:
  name: ratings-service        # CAMBIAR: ratings → ratings-service
  namespace: cdps-29           # AÑADIR: namespace requerido
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment     # CAMBIAR: ratings-v1 → ratings-deployment
  namespace: cdps-29           # AÑADIR: namespace requerido
  labels:
    app: ratings
    version: v1
spec:
  replicas: 3                  # CAMBIAR: 1 → 3 (factor replicación 3)
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: cdps-ratings:g29  # CAMBIAR: <GROUP_NUMBER>/ratings → tu imagen
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: APP_VERSION      # AÑADIR: variable necesaria
          value: "v1"
        securityContext:
          runAsUser: 1000