apiVersion: v1
kind: Service
metadata:
  name: reviews-service        # CAMBIAR: reviews → reviews-service
  namespace: cdps-29           # AÑADIR: namespace requerido
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews