FROM python:3.9-slim

WORKDIR /opt/microservices/

COPY bookinfo/src/productpage/ .

RUN pip install --no-cache-dir -r requirements.txt
ENV SERVICES_DOMAIN=""
ENV DETAILS_HOSTNAME="details"
ENV RATINGS_HOSTNAME="ratings" 
ENV REVIEWS_HOSTNAME="reviews"
ENV TEAM_ID="29"
EXPOSE 9080

CMD ["python", "productpage.py", "9080"]